"""Generating one benchmark config per Type 1 dataset from a tool's tool.yaml."""

import importlib.util
from pathlib import Path

import pytest
import yaml

from molscout.bench.config import load_config
from molscout.bench.configs import TYPE1_DATASETS, make_configs

REPO = Path(__file__).resolve().parents[1]
SHA = "b" * 64
TOOL = {
    "tool": "reader",
    "name": "Reader",
    "version": "2.0.1 (git abc1234)",
    "python": "${STORE}/envs/reader/bin/python",
    "args": ["--checkpoint", "${STORE}/models/reader/model.pth", "--device", "cuda"],
    "checkpoints": [{"path": "${STORE}/models/reader/model.pth", "sha256": SHA}],
}
EXPECTED_PATHS = {
    "uspto": ("data/raw/uspto/USPTO", "data/raw/uspto/USPTO_mol_ref"),
    "uob": ("data/raw/uob/UOB", "data/raw/uob/UOB_mol_ref"),
    "jpo": ("data/raw/jpo/JPO", "data/raw/jpo/JPO_mol_ref"),
    "clef": ("data/raw/clef/CLEF", "data/raw/clef/CLEF_mol_ref"),
    "molrecbench_wild": ("data/raw/molrecbench_wild/images", "data/raw/molrecbench_wild"),
}


def write_tool(repo: Path, data: dict) -> Path:
    path = repo / "benchmarks" / "tools" / "structure_readers" / data["tool"] / "tool.yaml"
    path.parent.mkdir(parents=True)
    path.write_text(yaml.safe_dump(data, sort_keys=False))
    return path


def test_type1_datasets_are_the_five_crop_sets():
    assert {name: (paths.images, paths.references) for name, paths in TYPE1_DATASETS.items()} == EXPECTED_PATHS


def test_tool_yaml_gives_five_configs_that_load(tmp_path, monkeypatch):
    monkeypatch.setenv("STORE", "/store")
    tool_yaml = write_tool(tmp_path, TOOL)
    out = tmp_path / "benchmarks" / "configs"
    written = make_configs(tool_yaml, out, repo_root=tmp_path)
    assert [p.name for p in written] == [f"reader__{d}.yaml" for d in EXPECTED_PATHS]
    for path in written:
        assert path.parent == out
        assert path.read_text().splitlines()[0] == (
            "# Generated by scripts/make_configs.py from "
            "benchmarks/tools/structure_readers/reader/tool.yaml; edit that file and regenerate."
        )
        config = load_config(path, tmp_path)
        images, references = EXPECTED_PATHS[config.dataset]
        assert config.images == tmp_path / images
        assert config.references == tmp_path / references
        assert config.run_dir == tmp_path / "benchmarks" / "tools" / "structure_readers" / "reader"
        assert config.python == Path("/store/envs/reader/bin/python")
        assert config.args == ("--checkpoint", "/store/models/reader/model.pth", "--device", "cuda")
        assert config.tool_label == "Reader 2.0.1 (git abc1234)"


def test_configs_keep_the_plan_key_order_and_unexpanded_variables(tmp_path):
    data = {**TOOL, "env": {"PYSTOW_HOME": "${STORE}/models/reader"}, "lock_commands": [["java", "-version"]]}
    path = make_configs(write_tool(tmp_path, data), tmp_path / "configs", repo_root=tmp_path)[0]
    config = yaml.safe_load(path.read_text())
    assert list(config) == [
        "tool",
        "name",
        "version",
        "dataset",
        "images",
        "references",
        "run_dir",
        "python",
        "args",
        "checkpoints",
        "env",
        "lock_commands",
    ]
    assert config["python"] == "${STORE}/envs/reader/bin/python"
    assert config["env"] == {"PYSTOW_HOME": "${STORE}/models/reader"}
    assert config["lock_commands"] == [["java", "-version"]]


def test_generated_lock_commands_expand_when_the_config_loads(tmp_path, monkeypatch):
    monkeypatch.setenv("STORE", "/store")
    data = {**TOOL, "lock_commands": [["${STORE}/models/reader/jdk/bin/java", "-version"]]}
    path = make_configs(write_tool(tmp_path, data), tmp_path / "configs", repo_root=tmp_path)[0]
    assert yaml.safe_load(path.read_text())["lock_commands"] == [["${STORE}/models/reader/jdk/bin/java", "-version"]]
    assert load_config(path, tmp_path).lock_commands == (("/store/models/reader/jdk/bin/java", "-version"),)


def test_env_and_lock_commands_default_to_empty(tmp_path):
    path = make_configs(write_tool(tmp_path, TOOL), tmp_path / "configs", repo_root=tmp_path)[0]
    config = yaml.safe_load(path.read_text())
    assert (config["env"], config["lock_commands"]) == ({}, [])


@pytest.mark.parametrize(
    ("change", "message"),
    [
        ({"dataset": "uspto"}, r"unknown key\(s\): dataset"),
        ({"tool": "../escape"}, "tool must match"),
        ({"checkpoints": [{"path": "model.pth", "sha256": "short"}]}, "sha256"),
    ],
)
def test_bad_tool_yaml_is_rejected(tmp_path, change, message):
    tool_yaml = tmp_path / "tool.yaml"
    tool_yaml.write_text(yaml.safe_dump({**TOOL, **change}))
    with pytest.raises(ValueError, match=message):
        make_configs(tool_yaml, tmp_path / "configs", repo_root=tmp_path)
    assert not (tmp_path / "configs").exists()


def test_tool_folder_must_be_inside_the_repository(tmp_path):
    tool_yaml = write_tool(tmp_path / "outside", TOOL)
    with pytest.raises(ValueError, match="inside the repository"):
        make_configs(tool_yaml, tmp_path / "configs", repo_root=tmp_path / "repo")


def test_script_writes_configs_for_the_given_tool_yaml(tmp_path, capsys):
    spec = importlib.util.spec_from_file_location("make_configs", REPO / "scripts" / "make_configs.py")
    script = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(script)
    tool_yaml = write_tool(tmp_path, TOOL)
    out = tmp_path / "configs"
    assert script.main([str(tool_yaml), "--out", str(out), "--repo-root", str(tmp_path)]) == 0
    assert sorted(p.name for p in out.iterdir()) == sorted(f"reader__{d}.yaml" for d in EXPECTED_PATHS)
    assert capsys.readouterr().out.count("wrote ") == 5
