"""Benchmark configs for the Type 1 crop datasets, generated from each tool's tool.yaml."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType

import yaml

from molscout.bench.config import check_keys, check_tool_name, validate_config

TOOL_KEYS = ("tool", "name", "version", "python", "args", "checkpoints")
OPTIONAL_TOOL_KEYS = ("env", "lock_commands", "sources")
STRUCTURE_READERS = ("benchmarks", "tools", "structure_readers")
COMPLETE_SYSTEMS = ("benchmarks", "tools", "complete_systems")
HEADER = "# Generated by scripts/make_configs.py from {source}; edit that file and regenerate.\n"


@dataclass(frozen=True, slots=True)
class DatasetPaths:
    """A crop dataset's images folder and references, relative to the repository root."""

    images: str
    references: str


@dataclass(frozen=True, slots=True)
class PaperPaths:
    """A paper dataset's PDF folder, references and paper manifest, relative to the repository root."""

    pdfs: str
    references: str
    papers: str


# MolRecBench-Wild's references are its Parquet labels, read from the dataset root.
TYPE1_DATASETS = MappingProxyType(
    {
        "uspto": DatasetPaths("data/raw/uspto/USPTO", "data/raw/uspto/USPTO_mol_ref"),
        "uob": DatasetPaths("data/raw/uob/UOB", "data/raw/uob/UOB_mol_ref"),
        "jpo": DatasetPaths("data/raw/jpo/JPO", "data/raw/jpo/JPO_mol_ref"),
        "clef": DatasetPaths("data/raw/clef/CLEF", "data/raw/clef/CLEF_mol_ref"),
        "molrecbench_wild": DatasetPaths("data/raw/molrecbench_wild/images", "data/raw/molrecbench_wild"),
    }
)


TYPE2_DATASETS = MappingProxyType(
    {
        "biovista": PaperPaths("data/raw/biovista/pdfs", "data/raw/biovista", "data/manifests/biovista_papers.csv"),
        "internal": PaperPaths(
            "data/internal",
            "data/internal/ground_truth_SMILES_confirmed_1,2,4,6,16,19.csv",
            "data/manifests/internal_split.csv",
        ),
    }
)


def make_configs(tool_yaml: str | Path, out_dir: str | Path, *, repo_root: str | Path) -> list[Path]:
    """Write `<tool>__<dataset>.yaml` to out_dir; return the paths in dataset order.

    A tool.yaml under benchmarks/tools/structure_readers/ gives the five Type 1 crop configs, one under
    benchmarks/tools/complete_systems/ the two Type 2 paper configs. Every config is checked before any is
    written. `${VAR}` stays unexpanded until a run loads it.
    """
    tool_yaml = Path(tool_yaml).absolute()
    root = Path(repo_root).absolute()
    where = str(tool_yaml)
    try:
        data = yaml.safe_load(tool_yaml.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ValueError(f"{tool_yaml}: not valid YAML: {exc}") from None
    check_keys(data, TOOL_KEYS, OPTIONAL_TOOL_KEYS, where)
    check_tool_name(data["tool"], where)
    try:
        source = tool_yaml.relative_to(root).as_posix()
    except ValueError:
        raise ValueError(f"{tool_yaml}: the tool folder must be inside the repository {root}") from None
    parts = Path(source).parts
    if parts[:3] == STRUCTURE_READERS:
        datasets = {d: {"images": p.images, "references": p.references} for d, p in TYPE1_DATASETS.items()}
    elif parts[:3] == COMPLETE_SYSTEMS:
        datasets = {
            d: {"pdfs": p.pdfs, "references": p.references, "papers": p.papers} for d, p in TYPE2_DATASETS.items()
        }
    else:
        raise ValueError(
            f"{tool_yaml}: a tool.yaml belongs under benchmarks/tools/structure_readers/ or "
            "benchmarks/tools/complete_systems/"
        )
    run_dir = Path(source).parent.as_posix()
    texts: dict[Path, str] = {}
    for dataset, dataset_paths in datasets.items():
        config = {
            "tool": data["tool"],
            "name": data["name"],
            "version": data["version"],
            "dataset": dataset,
            **dataset_paths,
            "run_dir": run_dir,
            "python": data["python"],
            "args": data["args"],
            "checkpoints": data["checkpoints"],
            "env": data.get("env") or {},
            "lock_commands": data.get("lock_commands") or [],
        }
        if "sources" in data:
            config["sources"] = data["sources"]
        validate_config(config, where)
        body = yaml.safe_dump(config, sort_keys=False, allow_unicode=True, width=1000)
        texts[Path(out_dir) / f"{data['tool']}__{dataset}.yaml"] = HEADER.format(source=source) + body
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    for path, text in texts.items():
        path.write_text(text, encoding="utf-8")
    return list(texts)
